### PR TITLE
Update store.md to use combineReducers explicit call

### PR DESCRIPTION
**Pull request by ellbee**
As per commit 650f002 Remove combineReducers shortcut in favor of an explicit call

### CODE REVIEW

**Comment by gaearon** [comment]
I'd break into two subsections.

First subsection shows a basic example with two reducers and one master reducer that combines their results a la https://gist.github.com/gaearon/d77ca812015c0356654f.

Second subsection goes like “we already have a helper for that called `combineReducers`”.

**Comment by ellbee** [comment]
Yes, I like that approach. I'll update with changes.

**Comment by gaearon** [comment]
Thank you!

**Comment by ellbee** [comment]
Re-organized along the lines suggested by @gaearon.

**Comment by gaearon** [comment]
Good job, thank you!

**Pull request merged**
