### PR TITLE
Added an auto-generated change log.

### PR DESCRIPTION
**Pull request by dariocravero**
Before we go into `1.0`, here's a change log autogenerated from releases.
It doesn't make use of sections like _Added_, _Changed_ and _Fixed_ as we should but it's probably ok because it's imported. I think we should stick to those from now on. Thoughts?

### CODE REVIEW

**Comment by gaearon** [comment]
What does `[Unreleased][unreleased]` header mean?
How do we regenerate this changelog?

**Comment by dariocravero** [comment]
I put together [a little script](https://github.com/dariocravero/releases-to-changelog) to get the bulk of it in. I guess from there on we should be writing it ourselves as we commit stuff. That's to me the best way to go about it.
`[Unreleased][unreleased]` is a convention from [keepachangelog.com](http://keepachangelog.com/#how-can-i-minimize-the-effort-required-) to keep the release-to-be in there as we go. I guess we can remove one of them. That reminds me I didn't update the bottom of the file (the link to the latest stuff).

**Comment by dariocravero** [comment]
Updated!

**Comment by gaearon** [comment]
Oh, okay. Thanks a lot!

**Pull request merged**
