### PR TITLE
TodoMVC: Basic provider explanation and link

### PR DESCRIPTION
**Pull request by peteruithoven**
Also see: https://github.com/gaearon/redux/issues/397

### CODE REVIEW

**Comment by srph** [comment]
Isn't it preferred to make the Provider the top-most component?

```es6
React.render(
  <Provider store={store}>
    {() => <App /> }
  </Provider>,
  mountNode
);
```

**Comment by danmartinez101** [comment]
I believe that in order for hot reloading to work, the Provider component needs to be exported from a module. I'll try to find a reference.

**Comment by gaearon** [comment]
Don't worry about hot reloading yet. Right now to get hot reloading working you need an extra component, a la

```
const store = ...

export default class Root {
  render() {
    return (
      <Provider store={store}>
        {() => <App />}
      </Provider>
    );
  }
}
```

Later, we'll remove the need for extra component, when we solve #350.

**Comment by gaearon** [comment]
This is out of date, so closing. We need to go through examples to comment in a single take later.

**Pull request closed without merging**
