### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by gaearon**
This should (hopefully) finally fix the Windows build by removing env variables (since they're set on Windows in a different way, and I can't figure out how to make it work cross-platform).

@mikekidder, I'd appreciate you testing this!

### CODE REVIEW

**Comment by gaearon** [comment]
I've merged but let me know if something's off.

**Comment by hummlas** [comment]
There's a NPM package called _better-npm-run_ which allows you to set env variables in a cross-platform way.

I created a pull request for _react-redux-universal-hot-example_ which uses it: https://github.com/erikras/react-redux-universal-hot-example/pull/71

**Comment by gaearon** [comment]
Oh, neat. I'll stay with separate configs for now, but if I feel I need something more, I'll make sure to use it!

**Comment by mikekidder** [comment]
@gaearon All good on Windows with the separate configs!

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
