### PR TITLE
Flow type annotations

### PR DESCRIPTION
**Pull request by acdlite**
Opening this PR to track adding Flow annotations. So far I've completed Redux.js. Looks like the biggest thing we'll have to give up is `const`, as Flow supports neither that nor `let`. I think that trade off is worth it.

We'll also want to integrate Flow into our automated tests.

Prior to this my experience with Flow was the "Hello, World!" example on their website, so if I do something wrong please let me know :)

Addresses #83.

### CODE REVIEW

**Comment by gaearon** [comment]
Everything is `mixed` haha.

I like this. Want to see more :-)

**Comment by acdlite** [comment]
@gaearon Haha, that's a good thing in this case! Not making any assumptions about action or state types :)

**Comment by acdlite** [comment]
@gaearon How about this: I'll create a `types.js` file with all the basic types we deal with in Redux. We will have an Action and State type that simply aliases to `mixed`, for clarity.

**Comment by gaearon** [comment]
I like this.

**Comment by acdlite** [comment]
Still can't figure out how to use union types to implement function overloading.

**Comment by skevy** [comment]
I haven't tested this...but have you guys considered running the code base through babel first (and blacklisting flow so that it keeps the types) and then running it through the flow type checker? If that worked; it would allow all ES2015+ features to stay and still get the benefits of type checking.

**Comment by skevy** [comment]
Looks like this guy is doing it http://www.keendevelopment.ch/flow-babel-gulp-es6/

**Comment by ooflorent** [comment]
Why did you convert `const` to `var`?

**Comment by gaearon** [comment]
>Why did you convert const to var?

See the first post:

>Looks like the biggest thing we'll have to give up is const, as Flow supports neither that nor let.

Although it may be possible to do it some another way:

http://www.keendevelopment.ch/flow-babel-gulp-es6/

**Comment by acdlite** [comment]
I'm kind of stuck on this PR until someone can explain to me how to properly use union types to implement function overloading. Any Flow experts out there?

**Comment by taylorhakes** [comment]
I am not very familiar with Flow, but the issue is being caused by this line in createDispatcher.
```
return compose(...middlewares, dispatch);
```
If you take out dispatch, it stops complaining. I am not sure this is an issue with function overloading, but I am having a hard time figuring out what it wants.

I noticed https://github.com/gaearon/redux/pull/166 will conflict with this pull request. The issue may be solved because the createDispatcher function is being removed. 

Do you want me to take this over or would you like to continue? I can fix the code conflicted, add the code not covered in 166 and resubmit.

**Comment by acdlite** [comment]
We should probably wait until 1.0 when the API is stable. After that, feel free!

**Comment by winkler1** [comment]
Here's a way to run Flow when files change... very useful when tweaking the config, fast feedback loop.

`npm i --save-dev onchange && ./node_modules/onchange/cli.js '**/*' -- flow check`

**Comment by hzoo** [comment]
@acdlite About function overloading - http://flowtype.org/docs/union-intersection-types.html you can use intersections (`&`)

```js
// Intersections are well-suited to mimic function overloading.
declare var f: ((x: number) => void) & ((x: string) => void);
```

**Comment by gaearon** [comment]
Superseded by #87.

**Comment by gaearon** [comment]
Whoops, inception! I meant by #254.

**Pull request closed without merging**
