### PR TITLE
compiling react.js and react-native.js before npm publish

### PR DESCRIPTION
**Pull request by skevy**
The root react.js and react-native.js files need to be compiled with Babel before pushing to npm.

It's kind of nasty to have these long pre- and post-publish commands in package.json...so if you guys have interest in moving to a Makefile approach, let me know and I'll send another PR.

### CODE REVIEW

**Comment by acdlite** [comment]
Yeah, we should think about this. I like Make but when I used it in Flummox I got complaints from people that it made it harder for Windows users to contribute. Maybe a `scripts` folder with bash scripts would be better? I don't think we need the incremental build features of Make, just a way to run some predefined commands.

**Comment by skevy** [comment]
Scripts are fine too. I like `make`, but I understand the concerns from Windows users. I'll do something with scripts now and update this PR.

**Comment by dariocravero** [comment]
You may find these useful then :)
https://github.com/UXtemple/panels-router/tree/master/.bin we took it a
step further and use the same paths for compiled and source sending only
the necessary parts to npm and git but it's easy not to do that too if you
want to keep the current src structure.

**Comment by gaearon** [comment]
Let's keep ES6 versions of `react.js` and `react-native.js` in `src`.

>Maybe a scripts folder with bash scripts would be better?

Let's do this. The `build` script should put the compiled versions of `react.js` and `react-native.js` into the root folder. They should be in `.gitignore`.

**Comment by gaearon** [comment]
A temporary fix is out in https://github.com/gaearon/redux/commit/1ed784cc025d835d8fdf3812db2b8c2ec9d0fe2f.

**Comment by gaearon** [comment]
Meaning, it's out in 0.10.1..

**Comment by gaearon** [comment]
Do you mind rebasing this? Feel free to get rid of 1ed784cc025d835d8fdf3812db2b8c2ec9d0fe2f again, I just wanted to get a fix out and didn't notice you already updated the PR..

**Comment by skevy** [comment]
No problem. Will do after I push updates to #86.

**Comment by gaearon** [comment]
:+1:

**Comment by skevy** [comment]
@gaearon rebased.

**Comment by gaearon** [comment]
Cool, can you squash into a single commit please?

```
git checkout fix-packaging
git merge origin/master
git reset --soft origin/master
git commit -am "message"
git push -f
```

**Comment by skevy** [comment]
Sorry about that. Done.

**Comment by gaearon** [comment]
:+1: Thanks!

**Pull request merged**
