### PR TITLE
tests for the examples

### PR DESCRIPTION
**Pull request by sambs**
Supersedes #278

### CODE REVIEW

**Comment by gaearon** [comment]
Thank you! I'll look at it a bit later. Terrific work :-)

**Comment by quicksnap** [comment]
Before merging this, could you consider adding `{ cmd: 'npm', args: ['test'] }` to `examples/buildAll.js`? (You may need to rebase to latest to see that file.) This will cause the example tests to run on Travis.

**Comment by gaearon** [comment]
Thank you again. Wow.

**Comment by sambs** [comment]
Great! I'm glad I could help :-)

**Pull request merged**
