### PR TITLE
fix a typo in getting-started.md

### PR DESCRIPTION
**Pull request by chentsulin**

### CODE REVIEW

**Comment by acdlite** [comment]
Oh boy, this isn't actually a typo. It's an issue of style. Most American style guides dictate that commas should also go inside of quotation marks, even for titles and scare quotes. I believe the British style is more traditional. My programmer's mind has always preferred putting it on the outside, but in school and in formal writing situations — at least in America — the "correct" place is inside the quotation mark.

Thoughts, @gaearon?

**Comment by acdlite** [comment]
More info http://www.grammarly.com/answers/questions/4726-quotation-marks-and-other-punctuation-inside-or-outside/

**Comment by emmenko** [comment]
@acdlite interesting, didn't know that :)

**Comment by gaearon** [comment]
Pedants!
I'm fine with comma inside quote if that's what Americans do. ;-)

**Comment by acdlite** [comment]
Okay let's just close this then so we can be done talking about it :) Thanks for the PR, though, @chentsulin!

**Comment by chentsulin** [comment]
Good to know this. : ) Thanks for explanation.

**Pull request closed without merging**
