### PR TITLE
Removed .jsx from webpack config file, inside examples

### PR DESCRIPTION
**Pull request by djhojd**

### CODE REVIEW

**Comment by gaearon** [comment]
We don't really use JSX extension so there's no point. But. There's indeed a typo there. :-) There's no need for extra `?` at the end. I'd merge it if you fixed that in both examples' configs.

**Comment by djhojd** [comment]
Yes, here we do not use JSX but you have `extensions: ['', '.js', '.jsx']` and if someone would copy your webpack config file, take me for instance, and use .jsx it will end up patching your file :-).

**Comment by johanneslumpe** [comment]
Wouldn't it then be more appropriate to remove `.jsx` from the webpack config instead?

**Comment by emmenko** [comment]
@johanneslumpe yes

@djhojd please simply remove `.jsx` and the question mark in the regex

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
