### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DenisIzmaylov**

### CODE REVIEW

**Comment by gaearon** [comment]
I don't mind omitting parens when there is a single argument.

Do you folks think it reads better?

**Comment by emmenko** [comment]
I would also prefer no brackets for only one argument

**Comment by DenisIzmaylov** [comment]
Yes, I think it's more readable for almost people.
But we can vote in the community.
I fixed it according https://github.com/airbnb/javascript#arrow-functions which is basically using is default code style. Or do you prefer other?

**Comment by gaearon** [comment]
Let's go with Airbnb's style guide. But if we do that, I'd like to see eslint configuration to enforce as much of it as possible, and also update the source code.

**Comment by gaearon** [comment]
Closing in favor of #97.

**Pull request closed without merging**
