### PR TITLE
Test only public API and use better test data

### PR DESCRIPTION
**Pull request by emmenko**
@gaearon @acdlite it should be better now.

Refs https://github.com/gaearon/redux/pull/56#issuecomment-110797801

### CODE REVIEW

**Comment by emmenko** [comment]
@acdlite aaargh, too many breaking changes here :)

I will adjust the tests...

**Comment by acdlite** [comment]
:) You should just have to change the import paths.

**Comment by emmenko** [comment]
@acdlite done, ready-to-merge ;)

**Comment by acdlite** [comment]
Thanks!

**Comment by emmenko** [comment]
:+1:

**Comment by emmenko** [comment]
I don't know if you guys want to take over now, otherwise I can see if I can provide some tests for the React components...just let me know :)

**Comment by gaearon** [comment]
I'd appreciate component tests. You can use [shallow rendering](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) for that to avoid jsdom.

**Comment by emmenko** [comment]
Ok, I'll see what I can do. Besides that, I think you guys can already setup CI on travis...

**Comment by gaearon** [comment]
I'm going to be very busy in the next three weeks and won't participate as much. (Don't worry, I'll be back after ReactEurope :-). So things like setting up Travis, etc, are very welcome if @acdlite finds time, but I won't be able to focus on something like this just yet.

**Comment by acdlite** [comment]
I can handle that

**Pull request merged**
