### PR TITLE
Renamed argument to be more descriptive of its dual nature

### PR DESCRIPTION
**Pull request by johanneslumpe**
Everybody ok with that?

### CODE REVIEW

**Comment by ooflorent** [comment]
LGTM

**Comment by emmenko** [comment]
LGTM too. 

Refs #140

**Comment by johanneslumpe** [comment]
/cc @gaearon @acdlite 

If you guys are fine with this too I'll merge this on

**Comment by johanneslumpe** [comment]
Or like this ;)

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
