### PR TITLE
Set initial state in constructor

### PR DESCRIPTION
**Pull request by jamiehodge**
Replace if statement and extract getState method.

### CODE REVIEW

**Comment by acdlite** [comment]
I don't like this because the method names conflate React component state with the state from Redux. In other words, `this.getState()` and `this.setState()` are not symmetrical.

**Comment by jamiehodge** [comment]
Corrected

**Comment by jamiehodge** [comment]
I assume this is no-go:

````javascript
this.state = this.getState(props, context);

...

getState(props = this.props, context = this.context) {
  const state = context.redux.getState();
  return props.select(state);
}
````

**Comment by acdlite** [comment]
That's not the worst idea, but I still don't like how `this.setState()` and `this.getState()` refer to two different things.

**Comment by jamiehodge** [comment]
Well, given the method, I guess one could name it `selectState`.

**Comment by acdlite** [comment]
Thanks for the PR, but I'm going to close this since it's mostly style issue, and there's a reason for the way it currently is. If you can think of a way to change it that would improve clarity in a significant way, I'll re-open.

**Comment by acdlite** [comment]
Actually, yeah, I would consider `selectState()` if you want to try that.

**Comment by gaearon** [comment]
I'd avoid any purely stylistic changes until we have the tests.

**Comment by emmenko** [comment]
Tests are coming :) #56

**Pull request closed without merging**
