### PR TITLE
Lintify before running tests

### PR DESCRIPTION
**Pull request by emmenko**
Particularly useful for travis and for linting a PR.

/cc @gaearon

### CODE REVIEW

**Comment by gaearon** [comment]
I think Travis already lints because it runs prepublish during install, doesn't it?

**Comment by acdlite** [comment]
@gaearon Yes that's right

**Comment by acdlite** [comment]
Here's an example of a PR that fails linting on Travis https://travis-ci.org/gaearon/redux/builds/70258318

**Comment by emmenko** [comment]
Oh, right. Actually this kind of sucks about `npm`. 
I usually **run the tests** before publishing a package, which includes linting of course. So I'm sure I'm publishing a tested code. But using the `prepublish` script it runs also on `npm install`.

Personally I would rename `prepublish -> release`, and it has to be run manually with `npm run release` (and you can even setup automatic bumping of version, e.g.: https://www.npmjs.com/package/mversion).

**Comment by gaearon** [comment]
What's the right course of action here? Any more opinions? I'm an npm noob.

**Comment by emmenko** [comment]
Regardless of this PR, I think running tests + lint before publishing is important. But I don't think the `prepublish` task is appropriate in this case, since it executes on `npm install`.
I also personally find useful to have a task that automatically bumps the version, creates a tag and publish it.

But let's here what the others have to say :)

**Comment by valscion** [comment]
I was very surprised to see `redux` running some sort of build task (the `prepublish` one) when I installed it. If it isn't necessary to run when installing, then I'd suggest using `npm run release` (or the like) for release build specific tasks.

**Comment by gaearon** [comment]
@emmenko 

Can you update this PR to move build from `prepublish` to `release`?

And another thing: since you're changing build anyway, and it's simpler now, do you think you could fix #241? Basically this would mean moving the build back into NPM scripts like #9 attempted to do early on. I don't want to use shelljs (https://github.com/gaearon/redux/pull/94) as moving everything to the scripts seems simpler.

**Comment by emmenko** [comment]
@gaearon sure, will do that after work

**Comment by gaearon** [comment]
>Regardless of this PR, I think running tests + lint before publishing is important. But I don't think the prepublish task is appropriate in this case, since it executes on npm install.

I'm not sure this is entirely correct. It doesn't execute on *every* `npm install`.
See https://medium.com/@boennemann/what-is-npm-s-prepublish-and-why-is-it-so-confusing-a948373e6be1

**Comment by emmenko** [comment]
You're right, thanks for the link! :+1:

**Comment by emmenko** [comment]
Closed in favour of #267

**Pull request closed without merging**
