### PR TITLE
Remove React-specific code in favor of gaearon/redux-react

### PR DESCRIPTION
**Pull request by gaearon**
Per #230, the plan for 1.0 is to split Redux into two (I promise, just two!) packages:

* Redux core (this package)
* React bindings (http://github.com/gaearon/redux-react, not on NPM yet)

We'll have different UMD builds for each. It's slightly more pain for the common case, but I think it's justified because React bindings API needs more experimentation than the core API, and we don't want to bump core versions too fast, as all ecosystem (middleware, devtools, etc) will depend on it.

### CODE REVIEW

**Comment by gaearon** [comment]
If you use NPM though, the split will be as easy as depending on two packages instead of one, and replacing `redux/react` with `redux-react` in the source code.

**Comment by gaearon** [comment]
Also.. should that be redux-react or react-redux? I think I'm in favor of react-redux now, that's more natural for React ecosystem.

**Comment by acdlite** [comment]
Hey, but this is the Redux ecosystem :D

**Comment by gaearon** [comment]
Haha. I think Babel does the right thing: https://github.com/babel
Depending on the ecosystem, it chooses the project naming to “fit in”.

**Comment by acdlite** [comment]
I don't know if that's quite the same. Babel is a build tool, whereas Redux is a library. I prefer redux-react but I'm having trouble articulating why...

Is this to be a Redux library for React users, or a React library for Redux users?

**Comment by emmenko** [comment]
@gaearon do you plan to have just those bindings in the `*-react-*` repo or something else as well? If only bindings, would it make sense maybe to have a more specific naming? 
E.g.: `redux-react-bindings`...

**Comment by gaearon** [comment]
Global name needs to look non-awkward. `ReduxReactBindings` is awkward IMO. Both `ReduxReact` and `ReactRedux` look fine to me, but I like that `ReactRedux` (or `react-redux`) matches the dominant convention of React-related packages. Also some semi-official bindings use `react-` prefix (e.g. `react-art`).

**Comment by erikras** [comment]
In English, we generally put the adjective before the noun, and I think that in this case, `react` is modifying (naming a specific binding to a framework) `redux`.

It's a tight match, but I think I'm voting `react-redux`.

**Comment by acdlite** [comment]
If we're going to read it like an English phrase, then `react-redux` sounds like a new and improved version of React...

I think this a library for Redux users who also happen to use React, not React users who happen to use Redux. The difference between other projects like react-router is that React Router doesn't exist outside of the React ecosystem, whereas Redux could have redux-ember, redux-cycle, etc.

But I totally see the other argument. Meh. I don't care, I guess.

**Comment by gaearon** [comment]
>I think this a library for Redux users who also happen to use React, not React users who happen to use Redux.

That's the project maintainer speaking in you. For now, I expect the majority of users is likely to feel they're React users trying Redux, not the opposite. :-)

**Comment by gaearon** [comment]
We can always change later. For now I feel confident that's what'll cause least confusion.

**Comment by erikras** [comment]
Good arguments, @acdlite.

:-) "Well, we've got all our state in redux, but we want to switch rendering engines." LOL.

**Comment by emmenko** [comment]
> Global name needs to look non-awkward

It kinda feels awkward yes :)

> Meh. I don't care, I guess.

:+1:  

> We can always change later.

Agree.

**Comment by acdlite** [comment]
> :-) "Well, we've got all our state in redux, but we want to switch rendering engines." LOL.

Not much sillier than the inverse :)

**Comment by mattapperson** [comment]
Will the idea be to one day merge back into one?

**Comment by erikras** [comment]
Sounds like not, @mattapperson. The point is to abstract out the state-managing bits that are UI-agnostic.

@acdlite, touché. :-)

**Comment by gaearon** [comment]
@mattapperson 

I'd rather not. It's easier to evolve them separately, and in fact I'm sure somebody's going to come up with better API for the React part. This also signals that Redux is welcoming to Ember, Angular communities. We want everybody to have a great experience, not just our React friends.

**Comment by erikras** [comment]
I look forward to being able to introduce redux into my PrototypeJS app that I still manage. :sob: :gun:

**Comment by mattapperson** [comment]
@gaearon that makes sense. Thanks for the clarification!

**Comment by HenrikJoreteg** [comment]
For whatever its worth, huge plus 1 from me for splitting it up. Loving the patterns in redux (and its small filesize), but would love to be able to try using it with other renderers too as the number of options keep growing: https://twitter.com/HenrikJoreteg/status/619543358151634944

**Comment by paramaggarwal** [comment]
I vote for `redux-react`. As it's a extension of `redux` for `react`.

**Comment by dariocravero** [comment]
:+1: for `redux-react`, after all it's specific React functionality to work together with redux, so it kind of feel more natural to me.

**Comment by gaearon** [comment]
The opinions are split: https://twitter.com/dan_abramov/status/619976807995932673

**Pull request merged**
