### PR TITLE
Add script to help travis build all examples

### PR DESCRIPTION
**Pull request by quicksnap**
Doesn't run the tests yet, but can easily do so. If this looks good, Travis will need to run `npm build:examples`

### CODE REVIEW

**Comment by quicksnap** [comment]
This is good because at least if there are syntax errors with the examples it will catch them.

**Comment by quicksnap** [comment]
#157 #374

**Comment by gaearon** [comment]
This looks good per se, how do we make Travis run it now?

**Comment by quicksnap** [comment]
I don't know.. as the owner, do you have a way to make Travis run commands?

**Comment by quicksnap** [comment]
I'm reading up on Travis docs right now.. maybe somewhere in travis.yml

**Comment by quicksnap** [comment]
Nice! I modified the `travis.yml` and it did it. You can see the results here: https://travis-ci.org/gaearon/redux/builds/73478113

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
